package io.quarkus.ts.startstop.utils;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public enum CodeQuarkusExtensions {

    QUARKUS_RESTEASY_REACTIVE("quarkus-resteasy-reactive", "RESTEasy Reactive", "WJu", true),
    QUARKUS_RESTEASY_REACTIVE_JSONB("quarkus-resteasy-reactive-jsonb", "RESTEasy Reactive JSON-B", "sTz", true),
    QUARKUS_RESTEASY_REACTIVE_JACKSON("quarkus-resteasy-reactive-jackson", "RESTEasy Reactive Jackson", "tEq", true),
    QUARKUS_RESTEASY_REACTIVE_JAXB("quarkus-resteasy-reactive-jaxb", "RESTEasy Reactive JAXB", "Uku", false),
    QUARKUS_RESTEASY_REACTIVE_KOTLIN_SERIALIZATION("quarkus-resteasy-reactive-kotlin-serialization", "RESTEasy Reactive Kotlin Serialization", "9wf", false),
    QUARKUS_RESTEASY_REACTIVE_LINKS("quarkus-resteasy-reactive-links", "RESTEasy Reactive Links", "6hi", false),
    QUARKUS_RESTEASY_REACTIVE_QUTE("quarkus-resteasy-reactive-qute", "RESTEasy Reactive Qute", "X8W", false),
    QUARKUS_REST_CLIENT_REACTIVE("quarkus-rest-client-reactive", "REST Client Reactive", "6iu", true),
    QUARKUS_REST_CLIENT_REACTIVE_JACKSON("quarkus-rest-client-reactive-jackson", "REST Client Reactive Jackson", "Kcq", true),
    QUARKUS_REST_CLIENT_REACTIVE_JAXB("quarkus-rest-client-reactive-jaxb", "REST Client Reactive JAXB", "ignored", true),
    QUARKUS_REST_CLIENT_REACTIVE_JSONB("quarkus-rest-client-reactive-jsonb", "REST Client Reactive JSON-B", "ignored", true),
    QUARKUS_REST_CLIENT_REACTIVE_KOTLIN_SERIALIZATION("quarkus-rest-client-reactive-kotlin-serialization", "REST Client Reactive Kotlin Serialization", "65Z", false),

    // TODO Introduce buckets with reactive jax-rs extensions
    // To avoid java.lang.IllegalStateException: The 'quarkus-resteasy-reactive' and 'quarkus-resteasy' extensions cannot be used at the same time.
//    QUARKUS_RESTEASY("quarkus-resteasy", "RESTEasy JAX-RS", "98e", true),
//    QUARKUS_RESTEASY_JACKSON("quarkus-resteasy-jackson", "RESTEasy Jackson", "pV1", true),
//    QUARKUS_RESTEASY_JSONB("quarkus-resteasy-jsonb", "RESTEasy JSON-B", "49J", true),
//    QUARKUS_RESTEASY_JAXB("quarkus-resteasy-jaxb", "RESTEasy JAXB", "d7W", true),
//    QUARKUS_RESTEASY_MULTIPART("quarkus-resteasy-multipart", "RESTEasy Multipart", "kV0", true),
//    QUARKUS_RESTEASY_QUTE("quarkus-resteasy-qute", "RESTEasy Qute", "ju", false),
//    QUARKUS_RESTEASY_LINKS("quarkus-resteasy-links", "RESTEasy Links", "rK1", false),
//    QUARKUS_REST_CLIENT_MUTINY("quarkus-rest-client-mutiny", "Mutiny support for REST Client", "Ph0", false),
//    QUARKUS_REST_CLIENT("quarkus-rest-client", "REST Client", "ekA", true),
//    QUARKUS_REST_CLIENT_JAXB("quarkus-rest-client-jaxb", "REST Client JAXB", "8iY", true),
//    QUARKUS_REST_CLIENT_JSONB("quarkus-rest-client-jsonb", "REST Client JSON-B", "Q3z", true),
//    QUARKUS_REST_CLIENT_JACKSON("quarkus-rest-client-jackson", "REST Client Jackson", "pJg", true),

    QUARKUS_VERTX_GRAPHQL("quarkus-vertx-graphql", "Eclipse Vert.x GraphQL", "F9R", false),
    QUARKUS_HIBERNATE_VALIDATOR("quarkus-hibernate-validator", "Hibernate Validator", "YjV", true),
    //    https://github.com/quarkusio/quarkus/issues/26318
//    QUARKUS_HIBERNATE_ORM_REST_DATA_PANACHE("quarkus-hibernate-orm-rest-data-panache", "REST resources for Hibernate ORM with Panache", "CPa", false),
    //    https://github.com/quarkusio/quarkus/issues/26318
//    QUARKUS_MONGODB_REST_DATA_PANACHE("quarkus-mongodb-rest-data-panache", "REST resources for MongoDB with Panache", "2nT", false),
    // replaces quarkus-vertx-web - https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.3#reactive-routes
    QUARKUS_REACTIVE_ROUTES("quarkus-reactive-routes", "Reactive Routes", "0pm", true),
    QUARKUS_SMALLRYE_GRAPHQL("quarkus-smallrye-graphql", "SmallRye GraphQL", "jjB", true),
    QUARKUS_SMALLRYE_GRAPHQL_CLIENT("quarkus-smallrye-graphql-client", "SmallRye GraphQL Client", "5Jv", true),
    QUARKUS_SMALLRYE_JWT("quarkus-smallrye-jwt", "SmallRye JWT", "D9x", true),
    QUARKUS_SMALLRYE_OPENAPI("quarkus-smallrye-openapi", "SmallRye OpenAPI", "ARC", true),
    QUARKUS_UNDERTOW("quarkus-undertow", "Undertow Servlet", "LMC", true),
    QUARKUS_SMALLRYE_STORK("quarkus-smallrye-stork", "SmallRye Stork", "ignored", false),
    QUARKUS_WEBJARS_LOCATOR("quarkus-webjars-locator", "WebJar Locator", "XSP", false),
    QUARKUS_HAL("quarkus-hal", "Hypertext Application Language (HAL)", "ignored", false),
    QUARKUS_WEBSOCKETS("quarkus-websockets", "WebSockets", "JPE", true),
    QUARKUS_WEBSOCKETS_CLIENT("quarkus-websockets-client", "WebSockets Client", "YcS", true),
    QUARKUS_GRPC("quarkus-grpc", "gRPC", "iDg", true),
    QUARKUS_HIBERNATE_ORM("quarkus-hibernate-orm", "Hibernate ORM", "vH0", true),
    QUARKUS_HIBERNATE_ORM_PANACHE("quarkus-hibernate-orm-panache", "Hibernate ORM with Panache", "XZs", true),
    QUARKUS_JDBC_POSTGRESQL("quarkus-jdbc-postgresql", "JDBC Driver - PostgreSQL", "8IG", true),
    QUARKUS_JDBC_MARIADB("quarkus-jdbc-mariadb", "JDBC Driver - MariaDB", "78I", true),
    QUARKUS_JDBC_MYSQL("quarkus-jdbc-mysql", "JDBC Driver - MySQL", "9Be", true),
    QUARKUS_JDBC_MSSQL("quarkus-jdbc-mssql", "JDBC Driver - Microsoft SQL Server", "R6e", true),
    QUARKUS_JDBC_DB2("quarkus-jdbc-db2", "JDBC Driver - DB2", "bMO", false),
    QUARKUS_JDBC_H2("quarkus-jdbc-h2", "JDBC Driver - H2", "FBQ", false),
    QUARKUS_JDBC_DERBY("quarkus-jdbc-derby", "JDBC Driver - Derby", "UCw", false),
    QUARKUS_JDBC_ORACLE("quarkus-jdbc-oracle", "JDBC Driver - Oracle", "H95", false),
    QUARKUS_REACTIVE_DB2_CLIENT("quarkus-reactive-db2-client", "Reactive DB2 client", "8XW", false),
    QUARKUS_REACTIVE_MSSQL_CLIENT("quarkus-reactive-mssql-client", "Reactive MS SQL client", "zGY", false),
    QUARKUS_REACTIVE_MYSQL_CLIENT("quarkus-reactive-mysql-client", "Reactive MySQL client", "fmW", true),
    QUARKUS_REACTIVE_ORACLE_CLIENT("quarkus-reactive-oracle-client", "Reactive Oracle client", "sQm", false),
    QUARKUS_REACTIVE_PG_CLIENT("quarkus-reactive-pg-client", "Reactive PostgreSQL client", "ih0", true),
    QUARKUS_AGROAL("quarkus-agroal", "Agroal - Database connection pool", "qiu", true),
    // The Blaze-Persistence dependency is present but no persistence units have been defined.
    // BLAZE_PERSISTENCE_INTEGRATION_QUARKUS("blaze-persistence-integration-quarkus", "Blaze-Persistence", "weW", false),
    QUARKUS_CACHE("quarkus-cache", "Cache", "W1i", true),
    // https://issues.redhat.com/browse/QUARKUS-1295
//    QUARKUS_ELASTICSEARCH_REST_HIGH_LEVEL_CLIENT("quarkus-elasticsearch-rest-high-level-client", "Elasticsearch REST High Level Client", "OJe", false),
    QUARKUS_ELASTICSEARCH_REST_CLIENT("quarkus-elasticsearch-rest-client", "Elasticsearch REST client", "NhW", false),
    QUARKUS_FLYWAY("quarkus-flyway", "Flyway", "wTM", false),
    QUARKUS_HAZELCAST_CLIENT("quarkus-hazelcast-client", "Hazelcast Client", "yii", false),
    QUARKUS_HIBERNATE_ENVERS("quarkus-hibernate-envers", "Hibernate Envers", "8j9", false),
    QUARKUS_HIBERNATE_ORM_PANACHE_KOTLIN("quarkus-hibernate-orm-panache-kotlin", "Hibernate ORM with Panache and Kotlin", "O3q", false),
    QUARKUS_HIBERNATE_REACTIVE("quarkus-hibernate-reactive", "Hibernate Reactive", "r1s", false),
    QUARKUS_HIBERNATE_REACTIVE_PANACHE("quarkus-hibernate-reactive-panache", "Hibernate Reactive with Panache", "20r", false),
    QUARKUS_HIBERNATE_REACTIVE_REST_DATA_PANACHE("quarkus-hibernate-reactive-rest-data-panache", "REST resources for Hibernate Reactive with Panache", "ignored", false),
    QUARKUS_HIBERNATE_SEARCH_ORM_ELASTICSEARCH("quarkus-hibernate-search-orm-elasticsearch", "Hibernate Search + Elasticsearch", "oHk", true),
    QUARKUS_HIBERNATE_SEARCH_ORM_COORDINATION_OUTBOX_POLLING("quarkus-hibernate-search-orm-coordination-outbox-polling", "Hibernate Search Coordination with Outbox Polling", "HoS", false),
    QUARKUS_INFINISPAN_CLIENT("quarkus-infinispan-client", "Infinispan Client", "sOv", true),
    // quarkus-liquibase expects available datasource, we are running without dev services to avoid Docker dependency
//    QUARKUS_LIQUIBASE("quarkus-liquibase", "Liquibase", "Xkd", false),
    QUARKUS_LIQUIBASE_MONGODB("quarkus-liquibase-mongodb", "Liquibase MongoDB", "QWC", false),
    QUARKUS_MONGODB_CLIENT("quarkus-mongodb-client", "MongoDB client", "ThS", false),
    QUARKUS_MONGODB_PANACHE("quarkus-mongodb-panache", "MongoDB with Panache", "y3v", false),
    QUARKUS_MONGODB_PANACHE_KOTLIN("quarkus-mongodb-panache-kotlin", "MongoDB with Panache for Kotlin", "gT", false),
    QUARKUS_NARAYANA_JTA("quarkus-narayana-jta", "Narayana JTA - Transaction manager", "PBP", true),
    // Caused by: java.lang.IllegalStateException: 'quarkus-narayana-lra' can only work if 'quarkus-resteasy-jackson' or 'quarkus-resteasy-reactive-jackson' is present
    // QUARKUS_NARAYANA_LRA("quarkus-narayana-lra", "Narayana LRA - LRA Participant Support", "O8P", false),
    QUARKUS_NARAYANA_STM("quarkus-narayana-stm", "Narayana STM - Software Transactional Memory", "Nl9", false),
    // https://issues.redhat.com/browse/QUARKUS-1294
//    QUARKUS_REDIS_CLIENT("quarkus-redis-client", "Redis Client", "jlX", false),
    QUARKUS_SMALLRYE_REACTIVE_MESSAGING("quarkus-smallrye-reactive-messaging", "SmallRye Reactive Messaging", "Nts", true),
    // https://github.com/quarkusio/quarkus/issues/23383
//    QUARKUS_SMALLRYE_REACTIVE_MESSAGING_AMQP("quarkus-smallrye-reactive-messaging-amqp", "SmallRye Reactive Messaging - AMQP Connector", "ur3", true),
    QUARKUS_SMALLRYE_REACTIVE_MESSAGING_KAFKA("quarkus-smallrye-reactive-messaging-kafka", "SmallRye Reactive Messaging - Kafka Connector", "9qf", true),
    QUARKUS_SMALLRYE_REACTIVE_MESSAGING_MQTT("quarkus-smallrye-reactive-messaging-mqtt", "SmallRye Reactive Messaging - MQTT Connector", "ZsB", false),
    QUARKUS_SMALLRYE_REACTIVE_MESSAGING_RABBITMQ("quarkus-smallrye-reactive-messaging-rabbitmq", "SmallRye Reactive Messaging - RabbitMQ Connector", "haH", false),
    QUARKUS_QPID_JMS("quarkus-qpid-jms", "AMQP 1.0 JMS client - Apache Qpid JMS", "Zdm", false),
    QUARKUS_KAFKA_CLIENT("quarkus-kafka-client", "Apache Kafka Client", "FKK", true),
    // SRCFG00014: Property quarkus.kafka-streams.topics is required but the value was not found or is empty
    // https://github.com/quarkusio/quarkus/issues/8506
    // QUARKUS_KAFKA_STREAMS("quarkus-kafka-streams", "Apache Kafka Streams", "ShK", false),
    // SRCFG00014: Property quarkus.artemis.url is required but the value was not found or is empty
    // https://github.com/quarkusio/quarkus/issues/8506
    // QUARKUS_ARTEMIS_JMS("quarkus-artemis-jms", "Artemis JMS", "DWo", false),
    QUARKUS_CONFIG_YAML("quarkus-config-yaml", "YAML Configuration", "UAO", true),
    QUARKUS_CONFIG_CONSUL("quarkus-config-consul", "Consul Config", "qdi", false),
    QUARKUS_LOGGING_JSON("quarkus-logging-json", "Logging JSON", "7RG", true),
    QUARKUS_LOGGING_GELF("quarkus-logging-gelf", "Logging GELF", "wCO", false),
    QUARKUS_VERTX("quarkus-vertx", "Eclipse Vert.x", "WqB", true),
    QUARKUS_MUTINY("quarkus-mutiny", "Mutiny", "zqM", true),
    QUARKUS_REDIS_CLIENT("quarkus-redis-client", "Redis Client", "jlX", false),
    QUARKUS_SMALLRYE_CONTEXT_PROPAGATION("quarkus-smallrye-context-propagation", "SmallRye Context Propagation", "7pM", true),
    QUARKUS_KUBERNETES("quarkus-kubernetes", "Kubernetes", "dZK", false),
    QUARKUS_KIND("quarkus-kind", "Kind", "ignored", false),
    QUARKUS_OPENSHIFT("quarkus-openshift", "OpenShift", "Bqi", false),
    QUARKUS_SMALLRYE_HEALTH("quarkus-smallrye-health", "SmallRye Health", "tqK", true),
    QUARKUS_SMALLRYE_FAULT_TOLERANCE("quarkus-smallrye-fault-tolerance", "SmallRye Fault Tolerance", "vgg", true),
    QUARKUS_AMAZON_LAMBDA("quarkus-amazon-lambda", "AWS Lambda", "ia1", false),
    QUARKUS_AMAZON_LAMBDA_REST("quarkus-amazon-lambda-rest", "AWS Lambda Gateway REST API", "WSn", false),
    QUARKUS_AMAZON_LAMBDA_HTTP("quarkus-amazon-lambda-http", "AWS Lambda HTTP", "L0j", false),
    QUARKUS_AMAZON_LAMBDA_XRAY("quarkus-amazon-lambda-xray", "AWS Lambda X-Ray", "JsX", false),
    QUARKUS_AZURE_FUNCTIONS_HTTP("quarkus-azure-functions-http", "Azure Functions HTTP", "3YS", false),
    QUARKUS_CONTAINER_IMAGE_DOCKER("quarkus-container-image-docker", "Container Image Docker", "V9i", false),
    QUARKUS_CONTAINER_IMAGE_JIB("quarkus-container-image-jib", "Container Image Jib", "qZz", false),
    QUARKUS_CONTAINER_IMAGE_OPENSHIFT("quarkus-container-image-openshift", "Container Image OpenShift", "fPM", true),
    QUARKUS_CONTAINER_IMAGE_S2I("quarkus-container-image-s2i", "Container Image S2I", "pbs", false),
    QUARKUS_CONTAINER_IMAGE_BUILDPACK("quarkus-container-image-buildpack", "Container Image Buildpack", "ht6", false),
    QUARKUS_FUNQY_AMAZON_LAMBDA("quarkus-funqy-amazon-lambda", "Funqy AWS Lambda Binding", "Pqi", false),
    QUARKUS_FUNQY_GOOGLE_CLOUD_FUNCTIONS("quarkus-funqy-google-cloud-functions", "Funqy Google Cloud Functions", "K2H", false),
    QUARKUS_FUNQY_HTTP("quarkus-funqy-http", "Funqy HTTP Binding", "oru", false),
    QUARKUS_FUNQY_KNATIVE_EVENTS("quarkus-funqy-knative-events", "Funqy Knative Events Binding", "yZc", false),
    QUARKUS_GOOGLE_CLOUD_BIGQUERY("quarkus-google-cloud-bigquery", "Google Cloud Bigquery", "BZL", false),
    QUARKUS_GOOGLE_CLOUD_BIGTABLE("quarkus-google-cloud-bigtable", "Google Cloud Bigtable", "zNr", false),
    QUARKUS_GOOGLE_CLOUD_FIRESTORE("quarkus-google-cloud-firestore", "Google Cloud Firestore", "GEY", false),
    QUARKUS_GOOGLE_CLOUD_SPANNER("quarkus-google-cloud-spanner", "Google Cloud Spanner", "7w1", false),
    QUARKUS_GOOGLE_CLOUD_FUNCTIONS("quarkus-google-cloud-functions", "Google Cloud Functions", "Njx", false),
    QUARKUS_GOOGLE_CLOUD_FUNCTIONS_HTTP("quarkus-google-cloud-functions-http", "Google Cloud Functions HTTP", "Ej9", false),
    QUARKUS_GOOGLE_CLOUD_PUBSUB("quarkus-google-cloud-pubsub", "Google Cloud Pubsub", "Rbo", false),
    QUARKUS_GOOGLE_CLOUD_SECRET_MANAGER("quarkus-google-cloud-secret-manager", "Google Cloud Secret Manager", "HOX", false),
    QUARKUS_GOOGLE_CLOUD_STORAGE("quarkus-google-cloud-storage", "Google Cloud Storage", "Fii", false),
    QUARKUS_KUBERNETES_CLIENT("quarkus-kubernetes-client", "Kubernetes Client", "Spa", false),
    QUARKUS_KUBERNETES_CONFIG("quarkus-kubernetes-config", "Kubernetes Config", "VUX", false),
    QUARKUS_KUBERNETES_SERVICE_BINDING("quarkus-kubernetes-service-binding", "Kubernetes Service Binding", "8iE", false),
    QUARKUS_MINIKUBE("quarkus-minikube", "Minikube", "VUy", false),
    QUARKUS_OPENSHIFT_CLIENT("quarkus-openshift-client", "OpenShift Client", "CxU", false),
    QUARKUS_MICROMETER("quarkus-micrometer", "Micrometer metrics", "Svz", true),
    QUARKUS_MICROMETER_REGISTRY_PROMETHEUS("quarkus-micrometer-registry-prometheus", "Micrometer Registry Prometheus", "DTu", true),
    QUARKUS_OPENTELEMETRY("quarkus-opentelemetry", "OpenTelemetry", "y6J", false),
    QUARKUS_OPENTELEMETRY_EXPORTER_JAEGER("quarkus-opentelemetry-exporter-jaeger", "OpenTelemetry exporter: Jaeger", "DTW", false),
    QUARKUS_OPENTELEMETRY_EXPORTER_OTLP("quarkus-opentelemetry-exporter-otlp", "OpenTelemetry exporter: OTLP", "CGl", false),
    QUARKUS_SMALLRYE_METRICS("quarkus-smallrye-metrics", "SmallRye Metrics", "Ll4", false), //intentionally because of micrometer
    QUARKUS_SMALLRYE_OPENTRACING("quarkus-smallrye-opentracing", "SmallRye OpenTracing", "f7", true),
    QUARKUS_OIDC("quarkus-oidc", "OpenID Connect", "fgL", true),
    QUARKUS_ELYTRON_SECURITY_JDBC("quarkus-elytron-security-jdbc", "Elytron Security JDBC", "Pxs", false),
    QUARKUS_ELYTRON_SECURITY_LDAP("quarkus-elytron-security-ldap", "Elytron Security LDAP Realm", "z3K", false),
    QUARKUS_ELYTRON_SECURITY_OAUTH2("quarkus-elytron-security-oauth2", "Elytron Security OAuth 2.0", "9Ie", false),
    QUARKUS_ELYTRON_SECURITY_PROPERTIES_FILE("quarkus-elytron-security-properties-file", "Elytron Security Properties File", "Dk8", false),
    QUARKUS_KEYCLOAK_ADMIN_CLIENT("quarkus-keycloak-admin-client", "Keycloak Admin Client", "d1H", false),
    QUARKUS_KEYCLOAK_ADMIN_CLIENT_REACTIVE("quarkus-keycloak-admin-client-reactive", "Quarkus - Keycloak Admin Client - Reactive - Runtime", "ignored", false),
    QUARKUS_KEYCLOAK_AUTHORIZATION("quarkus-keycloak-authorization", "Keycloak Authorization", "2Bx", true),
    QUARKUS_OIDC_CLIENT("quarkus-oidc-client", "OpenID Connect Client", "wfZ", true),
    QUARKUS_OIDC_CLIENT_FILTER("quarkus-oidc-client-filter", "OpenID Connect Client Filter", "T0U", true),
    // TODO Introduce buckets with reactive jax-rs extensions
//    QUARKUS_OIDC_CLIENT_REACTIVE_FILTER("quarkus-oidc-client-reactive-filter", "OpenID Connect Client Filter Reactive", "YqA", false),
    // TODO Introduce buckets with reactive jax-rs extensions
//    QUARKUS_OIDC_TOKEN_PROPAGATION_REACTIVE("quarkus-oidc-token-propagation-reactive", "OpenID Connect Token Propagation Reactive", "ignored", false),
    QUARKUS_OIDC_TOKEN_PROPAGATION("quarkus-oidc-token-propagation", "OpenID Connect Token Propagation", "Bg9", false),
    QUARKUS_SECURITY_JPA("quarkus-security-jpa", "Security JPA", "W8w", false),
    QUARKUS_SECURITY_WEBAUTHN("quarkus-security-webauthn", "Security WebAuthn", "ignored", false),
    QUARKUS_SMALLRYE_JWT_BUILD("quarkus-smallrye-jwt-build", "SmallRye JWT Build", "Phi", true),
    QUARKUS_VAULT("quarkus-vault", "Vault", "ZRf", false),
    QUARKUS_AVRO("quarkus-avro", "Apache Avro", "Aas", true),
    QUARKUS_AWT("quarkus-awt", "AWT", "zo3", false),
    QUARKUS_APICURIO_REGISTRY_AVRO("quarkus-apicurio-registry-avro", "Apicurio Registry - Avro", "Akz", false),
    QUARKUS_CONFLUENT_REGISTRY_AVRO("quarkus-confluent-registry-avro", "Confluent Schema Registry - Avro", "ignored", false),
    QUARKUS_JAXB("quarkus-jaxb", "JAXB", "BHf", true),
    QUARKUS_JSONB("quarkus-jsonb", "JSON-B", "TPK", true),
    QUARKUS_JSONP("quarkus-jsonp", "JSON-P", "TPY", true),
    QUARKUS_JACKSON("quarkus-jackson", "Jackson", "bapn", true),
    QUARKUS_JACOCO("quarkus-jacoco", "Jacoco - Code Coverage", "r3r", false),
    QUARKUS_JGIT("quarkus-jgit", "JGit", "C53", false),
    QUARKUS_MAILER("quarkus-mailer", "Mailer", "baLo", false),
    QUARKUS_PICOCLI("quarkus-picocli", "Picocli", "UX2", false),
    QUARKUS_QUARTZ("quarkus-quartz", "Quartz", "8YL", true),
    QUARKUS_QUTE("quarkus-qute", "Qute Templating", "xTN", false),
    QUARKUS_SCHEDULER("quarkus-scheduler", "Scheduler - tasks", "CBv", true),
    QUARKUS_SPRING_BOOT_PROPERTIES("quarkus-spring-boot-properties", "Quarkus Extension for Spring Boot properties", "XkM", true),
    QUARKUS_SPRING_CACHE("quarkus-spring-cache", "Quarkus Extension for Spring Cache API", "DG", true),
    QUARKUS_SPRING_CLOUD_CONFIG_CLIENT("quarkus-spring-cloud-config-client", "Quarkus Extension for Spring Cloud Config Client", "egg", true),
    QUARKUS_SPRING_DI("quarkus-spring-di", "Quarkus Extension for Spring DI API", "VOH", true),
    QUARKUS_SPRING_DATA_JPA("quarkus-spring-data-jpa", "Quarkus Extension for Spring Data JPA API", "2ec", true),
    //    https://github.com/quarkusio/quarkus/issues/26318
//    QUARKUS_SPRING_DATA_REST("quarkus-spring-data-rest", "Quarkus Extension for Spring Data REST", "kdX", false),
    QUARKUS_SPRING_SCHEDULED("quarkus-spring-scheduled", "Quarkus Extension for Spring Scheduled", "RUR", true),
    QUARKUS_SPRING_SECURITY("quarkus-spring-security", "Quarkus Extension for Spring Security API", "mek", true),
    QUARKUS_SPRING_WEB("quarkus-spring-web", "Quarkus Extension for Spring Web API", "0D7", true),
    QUARKUS_KOTLIN("quarkus-kotlin", "Kotlin", "OxX", false),
    QUARKUS_SCALA("quarkus-scala", "Scala", "3e", false),
    QUARKUS_AMAZON_DYNAMODB("quarkus-amazon-dynamodb", "Amazon DynamoDB", "8QU", false),
    QUARKUS_AMAZON_IAM("quarkus-amazon-iam", "Amazon IAM", "m2P", false),
    QUARKUS_AMAZON_KMS("quarkus-amazon-kms", "Amazon KMS", "mqJ", false),
    QUARKUS_AMAZON_S3("quarkus-amazon-s3", "Amazon S3", "MUc", false),
    QUARKUS_AMAZON_SECRETSMANAGER("quarkus-amazon-secretsmanager", "Amazon Secrets Manager", "pVy", false),
    QUARKUS_AMAZON_SES("quarkus-amazon-ses", "Amazon SES", "kuJ", false),
    QUARKUS_AMAZON_SNS("quarkus-amazon-sns", "Amazon SNS", "kqe", false),
    QUARKUS_AMAZON_SQS("quarkus-amazon-sqs", "Amazon SQS", "koJ", false),
    QUARKUS_AMAZON_SSM("quarkus-amazon-ssm", "Amazon SSM", "knP", false),
    QUARKUS_AMAZON_COGNITO_USER_POOLS("quarkus-amazon-cognito-user-pools", "Amazon Cognito User Pools", "ignored", false),
    CAMEL_QUARKUS_CORE("camel-quarkus-core", "Camel Core", "8bB", false),
    CAMEL_QUARKUS_ACTIVEMQ("camel-quarkus-activemq", "Camel ActiveMQ", "EPu", false),
    CAMEL_QUARKUS_AMQP("camel-quarkus-amqp", "Camel AMQP", "maV", false),
    CAMEL_QUARKUS_ARANGODB("camel-quarkus-arangodb", "Camel ArangoDb", "NDy", false),
    CAMEL_QUARKUS_AS2("camel-quarkus-as2", "Camel AS2", "tqO", false),
    CAMEL_QUARKUS_AHC("camel-quarkus-ahc", "Camel Async HTTP Client (AHC)", "tl7", false),
    CAMEL_QUARKUS_AHC_WS("camel-quarkus-ahc-ws", "Camel Async HTTP Client (AHC) Websocket", "Mmt", false),
    CAMEL_QUARKUS_ATLASMAP("camel-quarkus-atlasmap", "Camel AtlasMap", "zj8", false),
    CAMEL_QUARKUS_ATOM("camel-quarkus-atom", "Camel Atom", "krt", false),
    CAMEL_QUARKUS_ATTACHMENTS("camel-quarkus-attachments", "Camel Attachments", "xl5", false),
    CAMEL_QUARKUS_AVRO("camel-quarkus-avro", "Camel Avro", "jUW", false),
    CAMEL_QUARKUS_JACKSON_AVRO("camel-quarkus-jackson-avro", "Camel Avro Jackson", "szA", false),
    CAMEL_QUARKUS_AVRO_RPC("camel-quarkus-avro-rpc", "Camel Avro RPC", "k21", false),
    CAMEL_QUARKUS_AWS2_ATHENA("camel-quarkus-aws2-athena", "Camel AWS 2 Athena", "hqL", false),
    CAMEL_QUARKUS_AWS2_CW("camel-quarkus-aws2-cw", "Camel AWS 2 CloudWatch", "xc", false),
    CAMEL_QUARKUS_AWS2_DDB("camel-quarkus-aws2-ddb", "Camel AWS 2 DynamoDB", "JWu", false),
    CAMEL_QUARKUS_AWS2_EC2("camel-quarkus-aws2-ec2", "Camel AWS 2 Elastic Compute Cloud (EC2)", "KaI", false),
    CAMEL_QUARKUS_AWS2_ECS("camel-quarkus-aws2-ecs", "Camel AWS 2 Elastic Container Service (ECS)", "KbL", false),
    CAMEL_QUARKUS_AWS2_EKS("camel-quarkus-aws2-eks", "Camel AWS 2 Elastic Kubernetes Service (EKS)", "KfL", false),
    CAMEL_QUARKUS_AWS2_EVENTBRIDGE("camel-quarkus-aws2-eventbridge", "Camel AWS 2 Eventbridge", "vD", false),
    CAMEL_QUARKUS_AWS2_IAM("camel-quarkus-aws2-iam", "Camel AWS 2 Identity and Access Management (IAM)", "LaF", false),
    CAMEL_QUARKUS_AWS2_KMS("camel-quarkus-aws2-kms", "Camel AWS 2 Key Management Service (KMS)", "LLL", false),
    CAMEL_QUARKUS_AWS2_KINESIS("camel-quarkus-aws2-kinesis", "Camel AWS 2 Kinesis", "Gyw", false),
    CAMEL_QUARKUS_AWS2_LAMBDA("camel-quarkus-aws2-lambda", "Camel AWS 2 Lambda", "v3L", false),
    CAMEL_QUARKUS_AWS2_MSK("camel-quarkus-aws2-msk", "Camel AWS 2 Managed Streaming for Apache Kafka (MSK)", "MjD", false),
    CAMEL_QUARKUS_AWS2_MQ("camel-quarkus-aws2-mq", "Camel AWS 2 MQ", "B7", false),
    CAMEL_QUARKUS_AWS2_S3("camel-quarkus-aws2-s3", "Camel AWS 2 S3 Storage Service", "D7", false),
    CAMEL_QUARKUS_AWS2_STS("camel-quarkus-aws2-sts", "Camel AWS 2 Security Token Service (STS)", "NPg", false),
    CAMEL_QUARKUS_AWS2_SES("camel-quarkus-aws2-ses", "Camel AWS 2 Simple Email Service (SES)", "NHL", false),
    CAMEL_QUARKUS_AWS2_SNS("camel-quarkus-aws2-sns", "Camel AWS 2 Simple Notification System (SNS)", "NMg", false),
    CAMEL_QUARKUS_AWS2_SQS("camel-quarkus-aws2-sqs", "Camel AWS 2 Simple Queue Service (SQS)", "NNL", false),
    CAMEL_QUARKUS_AWS2_TRANSLATE("camel-quarkus-aws2-translate", "Camel AWS 2 Translate", "67i", false),
    CAMEL_QUARKUS_AZURE_EVENTHUBS("camel-quarkus-azure-eventhubs", "Camel Azure Event Hubs", "CIe", false),
    CAMEL_QUARKUS_AZURE_STORAGE_BLOB("camel-quarkus-azure-storage-blob", "Camel Azure Storage Blob Service", "SjJ", false),
    CAMEL_QUARKUS_AZURE_STORAGE_QUEUE("camel-quarkus-azure-storage-queue", "Camel Azure Storage Queue Service", "dxp", false),
    CAMEL_QUARKUS_BASE64("camel-quarkus-base64", "Camel Base64", "siX", false),
    CAMEL_QUARKUS_BEAN("camel-quarkus-bean", "Camel Bean", "gys", false),
    CAMEL_QUARKUS_BEAN_VALIDATOR("camel-quarkus-bean-validator", "Camel Bean Validator", "bMp", false),
    CAMEL_QUARKUS_BINDY("camel-quarkus-bindy", "Camel Bindy", "xlc", false),
    CAMEL_QUARKUS_BOX("camel-quarkus-box", "Camel Box", "tFr", false),
    CAMEL_QUARKUS_BRAINTREE("camel-quarkus-braintree", "Camel Braintree", "MXc", false),
    CAMEL_QUARKUS_BROWSE("camel-quarkus-browse", "Camel Browse", "RwK", false),
    CAMEL_QUARKUS_CAFFEINE("camel-quarkus-caffeine", "Camel Caffeine Cache", "ku2", false),
    CAMEL_QUARKUS_CAFFEINE_LRUCACHE("camel-quarkus-caffeine-lrucache", "Camel Caffeine LRUCache", "IdP", false),
    CAMEL_QUARKUS_CASSANDRAQL("camel-quarkus-cassandraql", "Camel Cassandra CQL", "6kP", false),
    CAMEL_QUARKUS_CBOR("camel-quarkus-cbor", "Camel CBOR", "baso", false),
    CAMEL_QUARKUS_CONSUL("camel-quarkus-consul", "Camel Consul", "s5m", false),
    CAMEL_QUARKUS_CONTROLBUS("camel-quarkus-controlbus", "Camel Control Bus", "Lwz", false),
    CAMEL_QUARKUS_COUCHDB("camel-quarkus-couchdb", "Camel CouchDB", "cSm", false),
    CAMEL_QUARKUS_CRON("camel-quarkus-cron", "Camel Cron", "7ss", false),
    CAMEL_QUARKUS_CRYPTO("camel-quarkus-crypto", "Camel Crypto (JCE)", "e7p", false),
    CAMEL_QUARKUS_CSIMPLE("camel-quarkus-csimple", "Camel CSimple", "v1Z", false),
    CAMEL_QUARKUS_CSV("camel-quarkus-csv", "Camel CSV", "tWU", false),
    CAMEL_QUARKUS_DATAFORMAT("camel-quarkus-dataformat", "Camel Data Format", "oRh", false),
    CAMEL_QUARKUS_DEBEZIUM_MONGODB("camel-quarkus-debezium-mongodb", "Camel Debezium MongoDB Connector", "367", false),
    CAMEL_QUARKUS_DEBEZIUM_MYSQL("camel-quarkus-debezium-mysql", "Camel Debezium MySQL Connector", "vQa", false),
    CAMEL_QUARKUS_DEBEZIUM_POSTGRES("camel-quarkus-debezium-postgres", "Camel Debezium PostgresSQL Connector", "M6D", false),
    CAMEL_QUARKUS_DEBEZIUM_SQLSERVER("camel-quarkus-debezium-sqlserver", "Camel Debezium SQL Server Connector", "ycD", false),
    CAMEL_QUARKUS_DIGITALOCEAN("camel-quarkus-digitalocean", "Camel DigitalOcean", "dHw", false),
    CAMEL_QUARKUS_DIRECT("camel-quarkus-direct", "Camel Direct", "c8Z", false),
    CAMEL_QUARKUS_DISRUPTOR("camel-quarkus-disruptor", "Camel Disruptor", "nnM", false),
    CAMEL_QUARKUS_DOZER("camel-quarkus-dozer", "Camel Dozer", "9tO", false),
    CAMEL_QUARKUS_DROPBOX("camel-quarkus-dropbox", "Camel Dropbox", "GNG", false),
    CAMEL_QUARKUS_ELASTICSEARCH_REST("camel-quarkus-elasticsearch-rest", "Camel Elasticsearch Rest", "4Tk", false),
    CAMEL_QUARKUS_EXEC("camel-quarkus-exec", "Camel Exec", "PxD", false),
    CAMEL_QUARKUS_FHIR("camel-quarkus-fhir", "Camel FHIR", "LKT", false),
    CAMEL_QUARKUS_FILE("camel-quarkus-file", "Camel File", "Lt7", false),
    CAMEL_QUARKUS_FILE_WATCH("camel-quarkus-file-watch", "Camel File Watch", "evi", false),
    CAMEL_QUARKUS_FLATPACK("camel-quarkus-flatpack", "Camel Flatpack", "xN9", false),
    CAMEL_QUARKUS_FOP("camel-quarkus-fop", "Camel FOP", "uFj", false),
    CAMEL_QUARKUS_FREEMARKER("camel-quarkus-freemarker", "Camel Freemarker", "ILA", false),
    CAMEL_QUARKUS_FTP("camel-quarkus-ftp", "Camel FTP", "uHO", false),
    CAMEL_QUARKUS_GEOCODER("camel-quarkus-geocoder", "Camel Geocoder", "evQ", false),
    CAMEL_QUARKUS_GIT("camel-quarkus-git", "Camel Git", "uRS", false),
    CAMEL_QUARKUS_GITHUB("camel-quarkus-github", "Camel GitHub", "34H", false),
    CAMEL_QUARKUS_GOOGLE_BIGQUERY("camel-quarkus-google-bigquery", "Camel Google BigQuery", "Fgy", false),
    CAMEL_QUARKUS_GOOGLE_CALENDAR("camel-quarkus-google-calendar", "Camel Google Calendar", "p8U", false),
    CAMEL_QUARKUS_GOOGLE_DRIVE("camel-quarkus-google-drive", "Camel Google Drive", "kiA", false),
    CAMEL_QUARKUS_GOOGLE_MAIL("camel-quarkus-google-mail", "Camel Google Mail", "Z0L", false),
    CAMEL_QUARKUS_GOOGLE_PUBSUB("camel-quarkus-google-pubsub", "Camel Google Pubsub", "UlJ", false),
    CAMEL_QUARKUS_GOOGLE_SHEETS("camel-quarkus-google-sheets", "Camel Google Sheets", "Aws", false),
    CAMEL_QUARKUS_GOOGLE_STORAGE("camel-quarkus-google-storage", "Camel Google Storage", "Ckh", false),
    CAMEL_QUARKUS_GRAPHQL("camel-quarkus-graphql", "Camel GraphQL", "MSX", false),
    CAMEL_QUARKUS_GROK("camel-quarkus-grok", "Camel Grok", "Bsv", false),
    CAMEL_QUARKUS_GRPC("camel-quarkus-grpc", "Camel gRPC", "Br9", false),
    CAMEL_QUARKUS_GSON("camel-quarkus-gson", "Camel Gson", "BcX", false),
    CAMEL_QUARKUS_HAZELCAST("camel-quarkus-hazelcast", "Camel Hazelcast Atomic Number", "X86", false),
    CAMEL_QUARKUS_HEADERSMAP("camel-quarkus-headersmap", "Camel Headersmap", "FNE", false),
    CAMEL_QUARKUS_HL7("camel-quarkus-hl7", "Camel HL7", "u8T", false),
    CAMEL_QUARKUS_HTTP("camel-quarkus-http", "Camel HTTP", "taq", false),
    CAMEL_QUARKUS_HYSTRIX("camel-quarkus-hystrix", "Camel Hystrix", "UNf", false),
    CAMEL_QUARKUS_ICAL("camel-quarkus-ical", "Camel iCal", "pOZ", false),
    CAMEL_QUARKUS_INFINISPAN("camel-quarkus-infinispan", "Camel Infinispan", "QXx", false),
    CAMEL_QUARKUS_INFLUXDB("camel-quarkus-influxdb", "Camel InfluxDB", "P75", false),
    CAMEL_QUARKUS_IPFS("camel-quarkus-ipfs", "Camel IPFS", "mwS", false),
    CAMEL_QUARKUS_JACKSON("camel-quarkus-jackson", "Camel Jackson", "Sbp", false),
    CAMEL_QUARKUS_JACKSONXML("camel-quarkus-jacksonxml", "Camel JacksonXML", "RQA", false),
    CAMEL_QUARKUS_JAXB("camel-quarkus-jaxb", "Camel JAXB", "in0", false),
    CAMEL_QUARKUS_JDBC("camel-quarkus-jdbc", "Camel JDBC", "hOD", false),
    CAMEL_QUARKUS_JFR("camel-quarkus-jfr", "Camel Jfr", "vAQ", false),
    CAMEL_QUARKUS_JING("camel-quarkus-jing", "Camel Jing", "gs5", false),
    CAMEL_QUARKUS_JIRA("camel-quarkus-jira", "Camel Jira", "gra", false),
    CAMEL_QUARKUS_JMS("camel-quarkus-jms", "Camel JMS", "vEm", false),
    CAMEL_QUARKUS_JOHNZON("camel-quarkus-johnzon", "Camel Johnzon", "MqU", false),
    CAMEL_QUARKUS_JOLT("camel-quarkus-jolt", "Camel JOLT", "eYR", false),
    CAMEL_QUARKUS_JPA("camel-quarkus-jpa", "Camel JPA", "vFz", false),
    CAMEL_QUARKUS_JSLT("camel-quarkus-jslt", "Camel JSLT", "dYR", false),
    CAMEL_QUARKUS_JSONPATH("camel-quarkus-jsonpath", "Camel JSON Path", "kWp", false),
    CAMEL_QUARKUS_JSON_VALIDATOR("camel-quarkus-json-validator", "Camel JSON Schema Validator", "YZZ", false),
    CAMEL_QUARKUS_JSONB("camel-quarkus-jsonb", "Camel JSON-B", "N25", false),
    CAMEL_QUARKUS_JSONATA("camel-quarkus-jsonata", "Camel JSONATA", "qWC", false),
    CAMEL_QUARKUS_JTA("camel-quarkus-jta", "Camel JTA", "vHz", false),
    CAMEL_QUARKUS_KAFKA("camel-quarkus-kafka", "Camel Kafka", "ezA", false),
    CAMEL_QUARKUS_KAMELET("camel-quarkus-kamelet", "Camel Kamelet", "ES2", false),
    CAMEL_QUARKUS_KOTLIN("camel-quarkus-kotlin", "Camel Kotlin", "GsT", false),
    CAMEL_QUARKUS_KUBERNETES("camel-quarkus-kubernetes", "Camel Kubernetes", "9b3", false),
    CAMEL_QUARKUS_KUDU("camel-quarkus-kudu", "Camel Kudu", "7Ol", false),
    CAMEL_QUARKUS_LANGUAGE("camel-quarkus-language", "Camel Language", "CkM", false),
    CAMEL_QUARKUS_LEVELDB("camel-quarkus-leveldb", "Camel LevelDB", "x7e", false),
    CAMEL_QUARKUS_LOG("camel-quarkus-log", "Camel Log", "waa", false),
    CAMEL_QUARKUS_LRA("camel-quarkus-lra", "Camel LRA", "wbz", false),
    CAMEL_QUARKUS_LUMBERJACK("camel-quarkus-lumberjack", "Camel Lumberjack", "1TQ", false),
    CAMEL_QUARKUS_LZF("camel-quarkus-lzf", "Camel LZF Deflate Compression", "wfE", false),
    CAMEL_QUARKUS_MAIL("camel-quarkus-mail", "Camel Mail", "WgZ", false),
    CAMEL_QUARKUS_MASTER("camel-quarkus-master", "Camel Master", "AJs", false),
    CAMEL_QUARKUS_MICROMETER("camel-quarkus-micrometer", "Camel Micrometer", "RE8", false),
    CAMEL_QUARKUS_MICROPROFILE_FAULT_TOLERANCE("camel-quarkus-microprofile-fault-tolerance", "Camel Microprofile Fault Tolerance", "885", false),
    CAMEL_QUARKUS_MICROPROFILE_HEALTH("camel-quarkus-microprofile-health", "Camel MicroProfile Health", "OJ5", false),
    CAMEL_QUARKUS_MICROPROFILE_METRICS("camel-quarkus-microprofile-metrics", "Camel MicroProfile Metrics", "cvj", false),
    CAMEL_QUARKUS_MINIO("camel-quarkus-minio", "Camel Minio", "Bem", false),
    CAMEL_QUARKUS_MLLP("camel-quarkus-mllp", "Camel MLLP", "TuV", false),
    CAMEL_QUARKUS_MOCK("camel-quarkus-mock", "Camel Mock", "SO1", false),
    CAMEL_QUARKUS_MONGODB("camel-quarkus-mongodb", "Camel MongoDB", "Y9a", false),
    CAMEL_QUARKUS_MONGODB_GRIDFS("camel-quarkus-mongodb-gridfs", "Camel MongoDB GridFS", "rNa", false),
    CAMEL_QUARKUS_MSV("camel-quarkus-msv", "Camel MSV", "wrU", false),
    CAMEL_QUARKUS_MUSTACHE("camel-quarkus-mustache", "Camel Mustache", "Edg", false),
    CAMEL_QUARKUS_NAGIOS("camel-quarkus-nagios", "Camel Nagios", "fVt", false),
    CAMEL_QUARKUS_NATS("camel-quarkus-nats", "Camel Nats", "OqS", false),
    CAMEL_QUARKUS_NETTY("camel-quarkus-netty", "Camel Netty", "frc", false),
    CAMEL_QUARKUS_NETTY_HTTP("camel-quarkus-netty-http", "Camel Netty HTTP", "Bl8", false),
    CAMEL_QUARKUS_NITRITE("camel-quarkus-nitrite", "Camel Nitrite", "538", false),
    CAMEL_QUARKUS_NSQ("camel-quarkus-nsq", "Camel NSQ", "wHk", false),
    CAMEL_QUARKUS_OAIPMH("camel-quarkus-oaipmh", "Camel OAI-PMH", "I1i", false),
    CAMEL_QUARKUS_OLINGO4("camel-quarkus-olingo4", "Camel Olingo4", "8YU", false),
    CAMEL_QUARKUS_OPENAPI_JAVA("camel-quarkus-openapi-java", "Camel OpenAPI Java", "Hbh", false),
    CAMEL_QUARKUS_OPENSTACK("camel-quarkus-openstack", "Camel OpenStack", "ntQ", false),
    CAMEL_QUARKUS_OPENTELEMETRY("camel-quarkus-opentelemetry", "Camel OpenTelemetry", "DlR", false),
    CAMEL_QUARKUS_OPENTRACING("camel-quarkus-opentracing", "Camel OpenTracing", "0Q1", false),
    CAMEL_QUARKUS_OPTAPLANNER("camel-quarkus-optaplanner", "Camel OptaPlanner", "Xai", false),
    CAMEL_QUARKUS_PAHO("camel-quarkus-paho", "Camel Paho", "y2W", false),
    CAMEL_QUARKUS_PAHO_MQTT5("camel-quarkus-paho-mqtt5", "Camel Paho MQTT5", "Bfa", false),
    CAMEL_QUARKUS_PDF("camel-quarkus-pdf", "Camel PDF", "w5E", false),
    CAMEL_QUARKUS_PLATFORM_HTTP("camel-quarkus-platform-http", "Camel Platform HTTP", "d0M", false),
    CAMEL_QUARKUS_PGEVENT("camel-quarkus-pgevent", "Camel PostgresSQL Event", "P3X", false),
    CAMEL_QUARKUS_PG_REPLICATION_SLOT("camel-quarkus-pg-replication-slot", "Camel PostgresSQL Replication Slot", "Oux", false),
    CAMEL_QUARKUS_PROTOBUF("camel-quarkus-protobuf", "Camel Protobuf", "odV", false),
    CAMEL_QUARKUS_JACKSON_PROTOBUF("camel-quarkus-jackson-protobuf", "Camel Protobuf Jackson", "KfV", false),
    CAMEL_QUARKUS_PUBNUB("camel-quarkus-pubnub", "Camel PubNub", "hWc", false),
    CAMEL_QUARKUS_QUARTZ("camel-quarkus-quartz", "Camel Quartz", "m26", false),
    CAMEL_QUARKUS_QUTE("camel-quarkus-qute", "Camel Qute", "mbB", false),
    CAMEL_QUARKUS_RABBITMQ("camel-quarkus-rabbitmq", "Camel RabbitMQ", "YFS", false),
    CAMEL_QUARKUS_REACTIVE_EXECUTOR("camel-quarkus-reactive-executor", "Camel Reactive Executor", "VH6", false),
    CAMEL_QUARKUS_REACTIVE_STREAMS("camel-quarkus-reactive-streams", "Camel Reactive Streams", "PEr", false),
    CAMEL_QUARKUS_REF("camel-quarkus-ref", "Camel Ref", "xz0", false),
    CAMEL_QUARKUS_REST("camel-quarkus-rest", "Camel Rest", "irm", false),
    CAMEL_QUARKUS_REST_OPENAPI("camel-quarkus-rest-openapi", "Camel REST OpenApi", "XJ8", false),
    CAMEL_QUARKUS_RSS("camel-quarkus-rss", "Camel RSS", "xHm", false),
    CAMEL_QUARKUS_SAGA("camel-quarkus-saga", "Camel Saga", "bNa", false),
    CAMEL_QUARKUS_SALESFORCE("camel-quarkus-salesforce", "Camel Salesforce", "Jip", false),
    CAMEL_QUARKUS_SAP_NETWEAVER("camel-quarkus-sap-netweaver", "Camel SAP NetWeaver", "EcI", false),
    CAMEL_QUARKUS_SCHEDULER("camel-quarkus-scheduler", "Camel Scheduler", "hqJ", false),
    CAMEL_QUARKUS_JSCH("camel-quarkus-jsch", "Camel SCP", "d4y", false),
    CAMEL_QUARKUS_SEDA("camel-quarkus-seda", "Camel SEDA", "OF", false),
    CAMEL_QUARKUS_SERVICENOW("camel-quarkus-servicenow", "Camel ServiceNow", "DqL", false),
    CAMEL_QUARKUS_SERVLET("camel-quarkus-servlet", "Camel Servlet", "sBr", false),
    CAMEL_QUARKUS_SHIRO("camel-quarkus-shiro", "Camel Shiro", "R2R", false),
    CAMEL_QUARKUS_SJMS("camel-quarkus-sjms", "Camel Simple JMS", "bavn", false),
    CAMEL_QUARKUS_SJMS2("camel-quarkus-sjms2", "Camel Simple JMS2", "Bxl", false),
    CAMEL_QUARKUS_SLACK("camel-quarkus-slack", "Camel Slack", "o0q", false),
    CAMEL_QUARKUS_SMALLRYE_REACTIVE_MESSAGING("camel-quarkus-smallrye-reactive-messaging", "Camel SmallRye Reactive Messaging", "Aow", false),
    CAMEL_QUARKUS_SNAKEYAML("camel-quarkus-snakeyaml", "Camel SnakeYAML", "4bb", false),
    CAMEL_QUARKUS_SOAP("camel-quarkus-soap", "Camel SOAP dataformat", "0lV", false),
    CAMEL_QUARKUS_SOLR("camel-quarkus-solr", "Camel Solr", "0go", false),
    CAMEL_QUARKUS_SPLUNK("camel-quarkus-splunk", "Camel Splunk", "4Il", false),
    CAMEL_QUARKUS_SPRING_RABBITMQ("camel-quarkus-spring-rabbitmq", "Camel Spring RabbitMQ", "bakw", false),
    CAMEL_QUARKUS_SQL("camel-quarkus-sql", "Camel SQL", "xVK", false),
    CAMEL_QUARKUS_SSH("camel-quarkus-ssh", "Camel SSH", "xWG", false),
    CAMEL_QUARKUS_STAX("camel-quarkus-stax", "Camel StAX", "87i", false),
    CAMEL_QUARKUS_STREAM("camel-quarkus-stream", "Camel Stream", "YQS", false),
    CAMEL_QUARKUS_STRINGTEMPLATE("camel-quarkus-stringtemplate", "Camel String Template", "oh2", false),
    CAMEL_QUARKUS_SYSLOG("camel-quarkus-syslog", "Camel Syslog", "boh", false),
    CAMEL_QUARKUS_TAGSOUP("camel-quarkus-tagsoup", "Camel TagSoup (a.k.a. TidyMarkup)", "Ggv", false),
    CAMEL_QUARKUS_TARFILE("camel-quarkus-tarfile", "Camel Tar File", "mub", false),
    CAMEL_QUARKUS_TELEGRAM("camel-quarkus-telegram", "Camel Telegram", "y44", false),
    CAMEL_QUARKUS_THREADPOOLFACTORY_VERTX("camel-quarkus-threadpoolfactory-vertx", "Camel ThreadPoolFactory Vert.x", "Yem", false),
    CAMEL_QUARKUS_TIKA("camel-quarkus-tika", "Camel Tika", "32F", false),
    CAMEL_QUARKUS_TIMER("camel-quarkus-timer", "Camel Timer", "Vcj", false),
    CAMEL_QUARKUS_TWILIO("camel-quarkus-twilio", "Camel Twilio", "wkU", false),
    CAMEL_QUARKUS_TWITTER("camel-quarkus-twitter", "Camel Twitter", "ySR", false),
    CAMEL_QUARKUS_UNIVOCITY_PARSERS("camel-quarkus-univocity-parsers", "Camel uniVocity CSV", "AQL", false),
    CAMEL_QUARKUS_VALIDATOR("camel-quarkus-validator", "Camel Validator", "42M", false),
    CAMEL_QUARKUS_VELOCITY("camel-quarkus-velocity", "Camel Velocity", "ZJp", false),
    CAMEL_QUARKUS_VERTX("camel-quarkus-vertx", "Camel Vert.x", "Lrd", false),
    CAMEL_QUARKUS_VERTX_HTTP("camel-quarkus-vertx-http", "Camel Vert.x HTTP Client", "M9a", false),
    CAMEL_QUARKUS_VERTX_WEBSOCKET("camel-quarkus-vertx-websocket", "Camel Vert.x WebSocket", "SHn", false),
    CAMEL_QUARKUS_VM("camel-quarkus-vm", "Camel VM", "4hL", false),
    CAMEL_QUARKUS_WEATHER("camel-quarkus-weather", "Camel Weather", "ST3", false),
    CAMEL_QUARKUS_XCHANGE("camel-quarkus-xchange", "Camel XChange", "4OK", false),
    CAMEL_QUARKUS_XML_IO_DSL("camel-quarkus-xml-io-dsl", "Camel XML IO DSL", "cYK", false),
    CAMEL_QUARKUS_XML_JAXB("camel-quarkus-xml-jaxb", "Camel XML JAXB", "18L", false),
    CAMEL_QUARKUS_XML_JAXP("camel-quarkus-xml-jaxp", "Camel XML JAXP", "18x", false),
    CAMEL_QUARKUS_XMLSECURITY("camel-quarkus-xmlsecurity", "Camel XML Security Sign", "hRT", false),
    CAMEL_QUARKUS_XPATH("camel-quarkus-xpath", "Camel XPath", "Q6t", false),
    CAMEL_QUARKUS_SAXON("camel-quarkus-saxon", "Camel XQuery", "Fxn", false),
    CAMEL_QUARKUS_XSLT("camel-quarkus-xslt", "Camel XSLT", "vvR", false),
    CAMEL_QUARKUS_XSTREAM("camel-quarkus-xstream", "Camel XStream", "eCC", false),
    CAMEL_QUARKUS_YAML_DSL("camel-quarkus-yaml-dsl", "Camel YAML DSL", "Zlx", false),
    CAMEL_QUARKUS_ZENDESK("camel-quarkus-zendesk", "Camel Zendesk", "wKG", false),
    CAMEL_QUARKUS_ZIP_DEFLATER("camel-quarkus-zip-deflater", "Camel Zip Deflate Compression", "Zw2", false),
    CAMEL_QUARKUS_ZIPFILE("camel-quarkus-zipfile", "Camel Zip File", "baW6", false),
    DEBEZIUM_QUARKUS_OUTBOX("debezium-quarkus-outbox", "Debezium Quarkus Outbox", "Zv2", false),
    KOGITO_QUARKUS("kogito-quarkus", "Kogito", "fYM", false),
    KOGITO_QUARKUS_DECISIONS("kogito-quarkus-decisions", "Kogito - Decisions (DMN)", "Uow", false),
    KOGITO_QUARKUS_PREDICTIONS("kogito-quarkus-predictions", "Kogito - Predictions (PMML)", "kFn", false),
    KOGITO_QUARKUS_RULES("kogito-quarkus-rules", "Kogito - Rules (DRL)", "GEm", false),
    KOGITO_QUARKUS_SERVERLESS_WORKFLOW("kogito-quarkus-serverless-workflow", "Kogito - Serverless Workflow", "mBP", false),
    OPTAPLANNER_QUARKUS("optaplanner-quarkus", "OptaPlanner (AI constraint solver)", "PHF", false),
    OPTAPLANNER_QUARKUS_BENCHMARK("optaplanner-quarkus-benchmark", "OptaPlanner benchmark", "UfB", false),
    OPTAPLANNER_QUARKUS_JSONB("optaplanner-quarkus-jsonb", "OptaPlanner JSON-B", "CWK", false),
    OPTAPLANNER_QUARKUS_JACKSON("optaplanner-quarkus-jackson", "OptaPlanner Jackson", "HNL", false);

    public final String id;
    public final String name;
    public final String shortId;
    public final boolean supported;

    CodeQuarkusExtensions(String id, String name, String shortId, boolean supported) {
        this.id = id;
        this.name = name;
        this.shortId = shortId;
        this.supported = supported;
    }

    public enum Flag {
        SUPPORTED,
        NOT_SUPPORTED,
        MIXED
    }

    public static List<List<CodeQuarkusExtensions>> partition(int buckets, Flag flag) {
        if (buckets < 1) {
            throw new IllegalArgumentException("Nope, buckets must be bigger than 0.");
        }
        List<CodeQuarkusExtensions> extensions = Stream.of(CodeQuarkusExtensions.values()).filter(x ->
                flag == Flag.SUPPORTED && x.supported ||
                        flag == Flag.NOT_SUPPORTED && !x.supported ||
                        flag == Flag.MIXED).collect(Collectors.toUnmodifiableList());
        if (buckets > extensions.size()) {
            buckets = extensions.size();
        }
        int chunk = extensions.size() / buckets;
        if (chunk < 1) {
            throw new IllegalArgumentException("Chunk must be bigger than 0. No supported extensions?");
        }
        List<List<CodeQuarkusExtensions>> result = new ArrayList<>();
        int i = 0;
        for (int j = 0; j < buckets; j++) {
            if (j + 1 == buckets) {
                // The last bucket is bigger if necessary
                result.add(new ArrayList<>(extensions.subList(i, extensions.size())));
            } else {
                result.add(new ArrayList<>(extensions.subList(i, Math.min(i + chunk, extensions.size()))));
            }
            i = i + chunk;
        }
        return result;
    }
}
